### PR TITLE
Add framework extras

### PR DESCRIPTION
**Pull request by aniket-magadum**
Some of the octobercms features depend on the ajax framework so it would be nice to have it included by default in the starter theme

### CODE REVIEW

**Comment by algoriq** [comment]
They are included by default in the themes /prismify-bootstrap-starter-kit/sources/js/app.js file.

**Comment by aniket-magadum** [comment]
I installed the theme but the data attributes were not working after putting framework extras it started to work

**Comment by algoriq** [comment]
> I installed the theme but the data attributes were not working after putting framework extras it started to work

I just checked, all ajax requests work correctly. Can you describe what actions you performed that led to this problem?

**Comment by aniket-magadum** [comment]
@algoriq Sorry I missed replying to this but actually the behavior of framework extras.js is missing like if I add  data-attach-loading to a button it is does not grey out and does not get disabled. It just behaves like a normal button

**Pull request merged**
